# Generated by Django 3.2.12 on 2023-08-03 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('industry', models.CharField(help_text='software, union, government,construction...', max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('membership_size', models.IntegerField(help_text='help for check on multple signup, can be updated if neccessary')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Unit_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unit_department',
                'verbose_name_plural': 'Unit_departments',
            },
        ),
        migrations.CreateModel(
            name='UserOrganzation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.organization')),
            ],
            options={
                'verbose_name': 'UserOrganzation',
                'verbose_name_plural': 'UserOrganzations',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('aspirant_start', models.BooleanField(default=False)),
                ('approved_all_contestant', models.BooleanField(default=False)),
                ('voting_start', models.BooleanField(default=False)),
                ('voting_end', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ElectionDepartment', to='election.unit_department')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ElectionOrganization', to='election.organization')),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
            },
        ),
    ]
