# Generated by Django 3.2.12 on 2023-08-05 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOrganzation',
            new_name='UserOrganization',
        ),
        migrations.AlterModelOptions(
            name='userorganization',
            options={'verbose_name': 'UserOrganization', 'verbose_name_plural': 'UserOrganizations'},
        ),
        migrations.AddField(
            model_name='unit_department',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_units', to='election.organization'),
        ),
    ]
