# Generated by Django 3.2.12 on 2023-08-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20230829_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='num_of_contestant',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
