# Generated by Django 3.2.12 on 2023-08-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_alter_position_num_of_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirant',
            name='name',
            field=models.CharField(blank=True, default='default name', max_length=50),
        ),
    ]
