# Generated by Django 3.2.12 on 2023-09-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_aspirant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='membership_size',
            field=models.IntegerField(help_text='help for counter overvotting, can be updated if neccessary'),
        ),
    ]
