# Generated by Django 3.2.12 on 2023-09-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_auto_20230911_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirant',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
