# Generated by Django 3.2.12 on 2023-09-11 16:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0010_auto_20230911_1521'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('user', 'election', 'organization_id')},
        ),
    ]
