# Generated by Django 3.2.12 on 2023-09-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_alter_voter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ElectionDepartment', to='election.unit_department'),
        ),
        migrations.AlterField(
            model_name='election',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ElectionOrganization', to='election.organization'),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='election.organization'),
        ),
    ]
