# Generated by Django 3.2.12 on 2023-09-12 17:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('election', '0012_auto_20230912_1723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aspirant',
            unique_together={('user', 'election')},
        ),
    ]
