# Generated by Django 3.2.12 on 2023-09-26 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_alter_aspirant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='election.voter'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'position', 'election')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
    ]
